(part "THVD1450D"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "R") (portType INOUT))
        (port "2" (symbPinId 2) (portName "%RE%") (portType INOUT))
        (port "3" (symbPinId 3) (portName "DE") (portType INOUT))
        (port "4" (symbPinId 4) (portName "D") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND") (portType INOUT))
        (port "6" (symbPinId 6) (portName "A") (portType INOUT))
        (port "7" (symbPinId 7) (portName "B") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VCC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "THVD1450D")
    (property "Mouser_Part_Number" "595-THVD1450D")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/THVD1450D?qs=chTDxNqvsylemUKR9F4kpw%3D%3D")
    (property "Arrow_Part_Number" "THVD1450D")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/thvd1450d/texas-instruments?region=europe")
    (property "Description" "3.3-V to 5-V RS-485 transceiver with +/-18-kV IEC ESD protection")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/THVD1450")
    (property "symbolName1" "THVD1450D")
)
